drawSessionBox (rangeTime, sessLable, boxLineColor, middleLineColor, bgColor) =>
    inSession = not na(time(timeframe.period, rangeTime, utcOffset))
    inExtend = not na(time(timeframe.period, rangeTime, utcOffset))
    startTime = 0
    startTime := inSession and not inSession[1] ? time : startTime[1]

    //Box lines
    var line lowHline = na
    var line topHline = na
    var line leftVline = na
    var line rightVline = na
    var line middleHline = na
    var box bgBox = na
    var label sLable = na

    var low_val = 0.0
    var high_val = 0.0
    var open_val = 0.0
    if inSession and not inSession[1]
        low_val := low
        high_val := high
        open_val := open
        high_val

    // Plot lines
    if inSession and ifMinuteBetween(1,59)
        if inSession[1]
            line.delete(lowHline)
            line.delete(topHline)
            line.delete(leftVline)
            line.delete(rightVline)
            line.delete(middleHline)
            box.delete(bgBox)
            label.delete(sLable)
            

        if low < low_val
            low_val := low
            low_val
        if high > high_val
            high_val := high
            high_val

        //Create Box
        //x1, y1, x2, y2
        if showBackground
            bgBox := fillSessionBox(startTime, high_val, low_val, bgColor)

        if showLines
            lowHline := drawSessionHline(startTime, low_val, boxLineColor)
            topHline := drawSessionHline(startTime, high_val, boxLineColor)
            if showVlines
                leftVline := line.new(startTime, high_val, startTime, low_val, xloc=xloc.bar_time, color=boxLineColor, style=line.style_solid, width=linesWidth)
                rightVline := line.new(time, high_val, time, low_val, xloc=xloc.bar_time, color=boxLineColor, style=line.style_solid, width=linesWidth)
            if showMiddleLine
                middleHline := drawSessionMline(startTime, high_val, low_val, middleLineColor)
        if showLable
            sLable := drawSessionLabel(startTime, high_val, sessLable, boxLineColor)

    else
        if inExtend and extendLines and not inSession and timeframe.isminutes
            time1 = line.get_x1(lowHline)
            time2 = line.get_x2(lowHline)
            price = line.get_y1(lowHline)
            line.delete(lowHline)
            lowHline := drawSessionHline(time1, price, boxLineColor)
            
            time1 := line.get_x1(topHline)
            time2 := line.get_x2(topHline)
            price := line.get_y1(topHline)
            line.delete(topHline)
            topHline := drawSessionHline(time1, price, boxLineColor)

            time1 := line.get_x1(middleHline)
            time2 := line.get_x2(middleHline)
            price := line.get_y1(middleHline)
            line.delete(middleHline)
            middleHline := drawSessionMline(time1, price, price, middleLineColor)
            middleHline


drawSessionBox(rangeTime1, sessLable1, boxLineColor1, middleLineColor1, bgColor1)