//Main Session 3
var GRP3 = "Session 3"
rangeTime3 = input.session(title='Session Time', defval='0700-1615', group=GRP3)

boxLineColor3 = input(color.green, 'Box and H/L Line Color', group=GRP3)
middleLineColor3 = input(color.green, 'Middle Line Color', group=GRP3)
bgColor3 = input(color.new(color.green, 90), 'Box Background Color', group=GRP3)



inSession3 = not na(time(timeframe.period, rangeTime3))
inExtend3 = not na(time(timeframe.period, extendTime))

startTime3 = 0
startTime3 := inSession3 and not inSession3[1] ? time : startTime3[1]

//Box lines
var line lowHline3 = na
var line topHline3 = na
var line leftVline3 = na
var line rightVline3 = na
var line middleHline3 = na
var box bgBox3 = na

var low_val3 = 0.0
var high_val3 = 0.0
if inSession3 and not inSession3[1]
    low_val3 := low
    high_val3 := high
    high_val3

// Plot lines
if inSession3 and timeframe.isintraday
    if inSession3[1]
        line.delete(lowHline3)
        line.delete(topHline3)
        line.delete(leftVline3)
        line.delete(rightVline3)
        line.delete(middleHline3)
        box.delete(bgBox3)

    if low < low_val3
        low_val3 := low
        low_val3
    if high > high_val3
        high_val3 := high
        high_val3

    //Create Box
    //x1, y1, x2, y2
    if showBackground
        bgBox3 := fillSessionBox(startTime3, high_val3, low_val3, bgColor3)

    if showLines
        lowHline3 := drawSessionHline(startTime3, low_val3, boxLineColor3)
        topHline3 := drawSessionHline(startTime3, high_val3, boxLineColor3)
        if showVlines
            leftVline3 := line.new(startTime3, high_val3, startTime3, low_val3, xloc=xloc.bar_time, color=boxLineColor3, style=line.style_solid, width=linesWidth)
            rightVline3 := line.new(time, high_val3, time, low_val3, xloc=xloc.bar_time, color=boxLineColor3, style=line.style_solid, width=linesWidth)
        if showMiddleLine
            middleHline3 := drawSessionMline(startTime3, high_val3, low_val3, middleLineColor3)

else
    if inExtend3 and extendLines and not inSession3 and timeframe.isintraday
        time1 = line.get_x1(lowHline3)
        time2 = line.get_x2(lowHline3)
        price = line.get_y1(lowHline3)
        line.delete(lowHline3)
        lowHline3 := drawSessionHline(time1, price, boxLineColor3)
        
        time1 := line.get_x1(topHline3)
        time2 := line.get_x2(topHline3)
        price := line.get_y1(topHline3)
        line.delete(topHline3)
        topHline3 := drawSessionHline(time1, price, boxLineColor3)

        time1 := line.get_x1(middleHline3)
        time2 := line.get_x2(middleHline3)
        price := line.get_y1(middleHline3)
        line.delete(middleHline3)
        middleHline3 := drawSessionMline(time1, price, price, middleLineColor3)
        middleHline3

