//Main Session 6
var GRP6 = "Session 6"
rangeTime6 = input.session(title='Session Time', defval='24x7', group=GRP6)
sessLable6 = input.string(defval = "WEEKLY", title = "Name", group = GRP6)
boxLineColor6 = input(color.orange, 'Box and H/L Line Color', group=GRP6)
middleLineColor6 = input(color.orange, 'Middle Line Color', group=GRP6)
bgColor6 = input(color.new(color.orange, 90), 'Box Background Color', group=GRP6)

drawSessBox(rangeTime6, sessLable6, boxLineColor6, middleLineColor6, bgColor6)